### PR TITLE
Update comments sniffs so that they work with CodeSniffer 2.0

### PR DESCRIPTION
**Pull request by DaazKu**
Had to rewrite most the of the content because CodeSniffer removed comment parsers.

I would like to note that the rewritten classes pass all tests but ClassNaming and "Long description must end with full stop"

### CODE REVIEW

**Comment by DaazKu** [comment]
Should resolve: #1

**Comment by linc** [comment]
Can you make a list of what test cases you did for this & the results? This type of change is a bit QA-heavy so a primer in the OP for cases like this would be helpful.

**Comment by DaazKu** [comment]
I literally tested every points listed in the classses' doc block.

Ex:

```
/**
 * Parses and verifies the doc comments for classes.
 *
 * Verifies that :
 * <ul>
 *  <li>A class doc comment exists.</li>
 *  <li>There is exactly one blank line before the class comment.</li>
 *  <li>Short description ends with a full stop.</li>
 *  <li>Long description ends with a full stop.</li>
 *  <li>There is a blank line between the description and the tags.</li>
 * </ul>
```

**Comment by R-J** [comment]
At first I've thought there has been a problem with changes getting lost, but I was just confusing repos...

**Pull request merged**
